apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: staging
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 361428600572.dkr.ecr.ap-south-1.amazonaws.com/jenkins-testin-repo-w:latest
        ports:
        - containerPort: 80
